swagger: "2.0"
info:
  version: "0.0.1"
  title: "network"
  description: "A simple service to get network info"
  termsOfService: "http://swagger.io/terms/"

  contact:
    name: "Cloudmesh REST Service"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /network:
    get:
      description: "Returns network details"
      produces:
        - "application/json"
      responses:

        "200":
          description: "network"
          schema:
            $ref: "#/definitions/network"


definitions:
  network:
    type: "object"
    required:
      - "network"
    properties:
	network:
        type: "string"
      

