swagger: "2.0"
info:
  version: "0.0.1"
  title: "network interface card info"
  description: "A simple service to get network interface card info as an example of using swagger -2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"

  contact:
    name: "Cloudmesh REST Service Example"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /network:
    get:
      description: "Returns network interface card info information of the hosting server"
      produces:
        - "application/json"
      responses:

        "200":
          description: "network interface card info"
          schema:
            $ref: "#/definitions/network"

definitions:
  network:
    type: "object"
    required:
      - "network"
    properties:
      model:
        type: "string"

 