---
swagger: "2.0"
info:
  description: "A simple service to get cpuinfo as an example of using swagger -2.0\
    \ specification and codegen"
  version: "0.0.1"
  title: "cpuinfo"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Cloudmesh REST Service Example"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /network:
    get:
      description: "Returns network information of the hosting server"
      operationId: "network_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Network info"
          schema:
            $ref: "#/definitions/NETWORK"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  NETWORK:
    type: "object"
    required:
    - "Network"
    properties:
      Network:
        type: "string"
    example:
      Network: "Network"
